from pathlib import Path
start_marker = '// ---- Pages principales'
end_marker = '// ---- School type specific search redirects'
new_block = """// ---- Pages principales\napp.get('/', (_req, res) => sendPublic(res, 'index.html'));\napp.get('/recherche', (_req, res) => sendPublic(res, 'recherche.html'));\napp.get('/avis', (_req, res) => sendPublic(res, 'avis.html'));\napp.get('/deposer-avis', (_req, res) => sendPublic(res, 'deposer-avis.html'));\napp.get('/a-propos', (_req, res) => sendPublic(res, 'a-propos.html'));\napp.get('/conditions', (_req, res) => sendPublic(res, 'conditions.html'));\napp.get('/confidentialite', (_req, res) => sendPublic(res, 'confidentialite.html'));\napp.get('/contact', (_req, res) => sendPublic(res, 'contact.html'));\napp.get('/sources', (_req, res) => sendPublic(res, 'sources.html'));\napp.get('/methode', (_req, res) => sendPublic(res, 'methode.html'));\napp.get('/faq', (_req, res) => sendPublic(res, 'faq.html'));\n\n// ---- Pages dynamiques\napp.get('/ville/:slug', (_req, res) => sendPublic(res, 'ville.html'));\napp.get('/academie/:slug', (_req, res) => sendPublic(res, 'academie.html'));\napp.get('/etablissement/:identifier', (_req, res) => sendPublic(res, 'etablissement.html'));\n\n// ---- Redirections legacy\napp.get(['/search', '/search.html'], (req, res) => {\n  const suffix = req.originalUrl.replace(/^\\/search(?:\\.html)?/, '');\n  return res.redirect(301, /recherche);\n});\napp.get(['/review', '/review.html'], (_req, res) => res.redirect(301, '/avis'));\napp.get(['/write-review', '/write-review.html'], (_req, res) => res.redirect(301, '/deposer-avis'));\napp.get(['/about', '/about.html'], (_req, res) => res.redirect(301, '/a-propos'));\napp.get(['/terms', '/terms.html'], (_req, res) => res.redirect(301, '/conditions'));\napp.get(['/privacy', '/privacy.html'], (_req, res) => res.redirect(301, '/confidentialite'));\napp.get(['/data-sources', '/data-sources.html'], (_req, res) => res.redirect(301, '/sources'));\napp.get(['/methodology', '/methodology.html'], (_req, res) => res.redirect(301, '/methode'));\napp.get(['/school', '/school.html'], (_req, res) => res.redirect(301, '/recherche'));\napp.get('/school/:identifier', (req, res) => {\n  const query = req.originalUrl.includes('?') ? req.originalUrl.slice(req.originalUrl.indexOf('?')) : '';\n  return res.redirect(301, /etablissement/);\n});\napp.get('/city/:slug', (req, res) => {\n  const query = req.originalUrl.includes('?') ? req.originalUrl.slice(req.originalUrl.indexOf('?')) : '';\n  return res.redirect(301, /ville/);\n});\napp.get('/local-authority/:slug', (req, res) => {\n  const query = req.originalUrl.includes('?') ? req.originalUrl.slice(req.originalUrl.indexOf('?')) : '';\n  return res.redirect(301, /academie/);\n});\n\n"""
path = Path('server.js')
text = path.read_text()
start = text.index(start_marker)
end = text.index(end_marker)
text = text[:start] + new_block + text[end:]
path.write_text(text)
